openapi: 3.0.1
servers:
  - url: https://sandbox-api.onsched.com
info:
  description: Endpoints for system utilities. e.g.Health
  title: OnSched API Utility
  version: v1
  x-apisguru-categories:
    - collaboration
  x-origin:
    - format: openapi
      url: https://sandbox-api.onsched.com/swagger/utility/swagger.json
      version: "3.0"
  x-providerName: onsched.com
  x-serviceName: utility
security:
  - oauth2:
      - OnSchedApi
paths:
  /utility/v1/health/heartbeat:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Success
      tags:
        - Health
components:
  securitySchemes:
    oauth2:
      flows:
        clientCredentials:
          scopes:
            OnSchedApi: Consumer and Setup Interface
          tokenUrl: https://sandbox-identity.onsched.com/connect/token
      type: oauth2
