language: node_js
node_js:
  - "8"
env:
  global:
    - GH_REF: "github.com/APIs-guru/openapi-directory.git"
deploy:
  - provider: script
    skip_cleanup: true
    script: 'git fetch --unshallow && npm run deploy'
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    local-dir: deploy
    fqdn: api.apis.guru
    github-token: $GH_DEPLOY_TOKEN
    keep-history: false
    on:
      branch: master

