language: node_js
node_js:
  - "8.3.0"
env:
  global:
    - GH_REF: "github.com/APIs-guru/api-models.git"
script:
  - travis_wait npm test
deploy:
  skip_cleanup: true
  provider: script
  script: 'git fetch --unshallow && npm run deploy'
  on:
    branch: master
