language: node_js
node_js:
  - 10
install:
  - npm i --no-optional
  - wget -O node_modules/swagger2openapi/schemas/openapi-3.0.json https://raw.githubusercontent.com/Mermade/oas-kit/master/packages/oas-validator/schemas/openapi-3.0.json
script:
  - node --max-old-space-size=8192 scripts/collection.js validate -q
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/deploy.sh
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    local-dir: deploy
    repo: APIs-guru/openapi-directory-api
    fqdn: api.apis.guru
    github-token: $GH_DEPLOY_TOKEN
    keep-history: false
    on:
      branch: master

