swagger: "2.0"
basePath: /api/
info:
  title: Georg API
  version: "1.0"
  x-apisguru-categories:
    - location
  x-origin:
    - format: swagger
      url: https://georg.nrm.se/api/swagger.json
      version: "2.0"
  x-providerName: nrm.se
  x-serviceName: georg
tags:
  - description: Georeference tool
    name: georg
paths:
  /coordinates:
    get:
      description: Returns status
      operationId: searchCoordinates
      parameters:
        - in: query
          name: coordinates
          required: false
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: string
      summary: Search coordinates in different formate
      tags:
        - georg
  /geoCoding:
    get:
      description: Return search results in json
      operationId: getGeoCode
      parameters:
        - in: query
          name: address
          required: false
          type: string
        - in: query
          name: source
          required: false
          type: string
        - in: query
          name: layer
          required: false
          type: string
        - in: query
          name: countryCode
          required: false
          type: string
        - format: int32
          in: query
          name: size
          required: false
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: string
      summary: Get geocoding
      tags:
        - georg
  /reverse:
    get:
      description: Returns status
      operationId: getReverseGeoCode
      parameters:
        - format: double
          in: query
          name: lat
          required: false
          type: number
        - format: double
          in: query
          name: lng
          required: false
          type: number
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: string
      summary: Get reverse geocoding
      tags:
        - georg
  /search:
    get:
      description: Return search results in json
      operationId: search
      parameters:
        - in: query
          name: text
          required: false
          type: string
        - in: query
          name: sources
          required: false
          type: string
        - in: query
          name: layers
          required: false
          type: string
        - in: query
          name: countryCode
          required: false
          type: string
        - format: int32
          in: query
          name: size
          required: false
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: string
      summary: Search
      tags:
        - georg
