swagger: '2.0'
schemes:
  - https
  - http
host: execute-api.amazonaws.com
basePath: /
info:
  contact:
    email: mike.ralphson@gmail.com
    name: Mike Ralphson
    url: 'https://github.com/mermade/aws2openapi'
    x-twitter: PermittedSoc
  description: 'The Amazon API Gateway Management API allows you to directly manage runtime aspects of your deployed APIs. To use it, you must explicitly set the SDK''s endpoint to point to the endpoint of your deployed API. The endpoint will be of the form https://{api-id}.execute-api.{region}.amazonaws.com/{stage}, or will be the endpoint corresponding to your API''s custom domain and base path, if applicable.'
  license:
    name: Apache 2.0 License
    url: 'http://www.apache.org/licenses/'
  termsOfService: 'https://aws.amazon.com/service-terms/'
  title: AmazonApiGatewayManagementApi
  version: '2018-11-29'
  x-apiClientRegistration:
    url: 'https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct'
  x-apisguru-categories:
    - cloud
  x-logo:
    backgroundColor: '#FFFFFF'
    url: 'https://twitter.com/awscloud/profile_image?size=original'
  x-origin:
    - contentType: application/json
      converter:
        url: 'https://github.com/mermade/aws2openapi'
        version: 1.0.0
      url: 'https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigatewaymanagementapi-2018-11-29.normal.json'
      x-apisguru-direct: true
  x-preferred: true
  x-providerName: amazonaws.com
  x-release: v4
  x-serviceName: apigatewaymanagementapi
externalDocs:
  description: Amazon Web Services documentation
  url: 'https://docs.aws.amazon.com/execute-api/'
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  hmac:
    description: Amazon Signature authorization v4
    in: header
    name: Authorization
    type: apiKey
    x-amazon-apigateway-authtype: awsSigv4
security:
  - hmac: []
parameters:
  X-Amz-Algorithm:
    in: header
    name: X-Amz-Algorithm
    required: false
    type: string
  X-Amz-Content-Sha256:
    in: header
    name: X-Amz-Content-Sha256
    required: false
    type: string
  X-Amz-Credential:
    in: header
    name: X-Amz-Credential
    required: false
    type: string
  X-Amz-Date:
    in: header
    name: X-Amz-Date
    required: false
    type: string
  X-Amz-Security-Token:
    in: header
    name: X-Amz-Security-Token
    required: false
    type: string
  X-Amz-Signature:
    in: header
    name: X-Amz-Signature
    required: false
    type: string
  X-Amz-SignedHeaders:
    in: header
    name: X-Amz-SignedHeaders
    required: false
    type: string
paths:
  '/@connections/{connectionId}':
    delete:
      description: Delete the connection with the provided id.
      operationId: DeleteConnection
      parameters:
        - description: ''
          in: path
          name: connectionId
          required: true
          type: string
      responses:
        '204':
          description: Success
        '480':
          description: GoneException
          schema:
            $ref: '#/definitions/GoneException'
        '481':
          description: LimitExceededException
          schema:
            $ref: '#/definitions/LimitExceededException'
        '482':
          description: ForbiddenException
          schema:
            $ref: '#/definitions/ForbiddenException'
    get:
      description: Get information about the connection with the provided id.
      operationId: GetConnection
      parameters:
        - description: ''
          in: path
          name: connectionId
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/GetConnectionResponse'
        '480':
          description: GoneException
          schema:
            $ref: '#/definitions/GoneException'
        '481':
          description: LimitExceededException
          schema:
            $ref: '#/definitions/LimitExceededException'
        '482':
          description: ForbiddenException
          schema:
            $ref: '#/definitions/ForbiddenException'
    parameters:
      - $ref: '#/parameters/X-Amz-Content-Sha256'
      - $ref: '#/parameters/X-Amz-Date'
      - $ref: '#/parameters/X-Amz-Algorithm'
      - $ref: '#/parameters/X-Amz-Credential'
      - $ref: '#/parameters/X-Amz-Security-Token'
      - $ref: '#/parameters/X-Amz-Signature'
      - $ref: '#/parameters/X-Amz-SignedHeaders'
    post:
      description: Sends the provided data to the specified connection.
      operationId: PostToConnection
      parameters:
        - description: The identifier of the connection that a specific client is using.
          in: path
          name: connectionId
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            properties:
              Data:
                description: The data to be sent to the client specified by its connection id.
                maxLength: 131072
                type: string
            required:
              - Data
            type: object
      responses:
        '200':
          description: Success
        '480':
          description: GoneException
          schema:
            $ref: '#/definitions/GoneException'
        '481':
          description: LimitExceededException
          schema:
            $ref: '#/definitions/LimitExceededException'
        '482':
          description: PayloadTooLargeException
          schema:
            $ref: '#/definitions/PayloadTooLargeException'
        '483':
          description: ForbiddenException
          schema:
            $ref: '#/definitions/ForbiddenException'
definitions:
  Data:
    description: The data to be sent to the client specified by its connection id.
    maxLength: 131072
    type: string
  DeleteConnectionRequest:
    properties: {}
    type: object
  ForbiddenException: {}
  GetConnectionRequest:
    properties: {}
    type: object
  GetConnectionResponse:
    properties:
      ConnectedAt:
        $ref: '#/definitions/__timestampIso8601'
        description: The time in ISO 8601 format for when the connection was established.
      Identity:
        $ref: '#/definitions/Identity'
      LastActiveAt:
        $ref: '#/definitions/__timestampIso8601'
        description: The time in ISO 8601 format for when the connection was last active.
    type: object
  GoneException: {}
  Identity:
    properties:
      SourceIp:
        $ref: '#/definitions/__string'
        description: The source IP address of the TCP connection making the request to API Gateway.
      UserAgent:
        $ref: '#/definitions/__string'
        description: The User Agent of the API caller.
    required:
      - SourceIp
      - UserAgent
    type: object
  LimitExceededException: {}
  PayloadTooLargeException: {}
  PostToConnectionRequest:
    properties:
      Data:
        $ref: '#/definitions/Data'
        description: The data to be sent to the client specified by its connection id.
    required:
      - Data
    type: object
  __string:
    type: string
  __timestampIso8601:
    format: date-time
    type: string
x-servers:
  - description: The AmazonApiGatewayManagementApi multi-region endpoint
    url: 'http://execute-api.{region}.amazonaws.com'
    variables:
      region:
        default: us-east-1
        description: The AWS region
        enum:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - us-gov-west-1
          - us-gov-east-1
          - ca-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-central-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-southeast-1
          - ap-southeast-2
          - ap-south-1
          - sa-east-1
  - description: The AmazonApiGatewayManagementApi multi-region endpoint
    url: 'https://execute-api.{region}.amazonaws.com'
    variables:
      region:
        default: us-east-1
        description: The AWS region
        enum:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - us-gov-west-1
          - us-gov-east-1
          - ca-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-central-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-southeast-1
          - ap-southeast-2
          - ap-south-1
          - sa-east-1
  - description: The AmazonApiGatewayManagementApi endpoint for China (Beijing) and China (Ningxia)
    url: 'http://execute-api.{region}.amazonaws.com.cn'
    variables:
      region:
        default: cn-north-1
        description: The AWS region
        enum:
          - cn-north-1
          - cn-northwest-1
  - description: The AmazonApiGatewayManagementApi endpoint for China (Beijing) and China (Ningxia)
    url: 'https://execute-api.{region}.amazonaws.com.cn'
    variables:
      region:
        default: cn-north-1
        description: The AWS region
        enum:
          - cn-north-1
          - cn-northwest-1
