openapi: 3.0.3
servers:
  - url: ","
info:
  contact: {}
  description: >-
    Welcome to the official API of the brainbi platform. Using this API you can freely integrate our analytics platform with any other solution. 

    Please refer to the following documentation and in case of any issues, please contact us at service@brainbi.net.


    Please note: for this API you will use your email and password from the brainbi.net platform to gather a Bearer Token for any API calls (use Login and get token). Once you are finished with your calls, please do a logout to remove your token and keep your account safe (use logout).
  title: brainbi
  version: 1.0.0
  x-apisguru-categories:
    - ecommerce
  x-origin:
    - format: postman
      url: https://www.postman.com/collections/1148203-6a9d2dc5-3f7e-47f5-ae7d-782740625908-SzKZtGPb
      version: 2.x
  x-preferred: null
  x-providerName: brainbi.net
tags:
  - name: Pricing Rules
  - name: Products
  - name: Customers
  - name: Orders
  - name: OrderLines
paths:
  /api/customers:
    get:
      description: This resource lists all cusomters that are currently saved in your account.
      operationId: customers
      parameters:
        - in: query
          name: ""
          schema:
            example: ""
            type: string
      responses:
        "200":
          description: ""
      summary: Customers
      tags:
        - Customers
  /api/login:
    post:
      description: Use this endpoint to make the initial call with your email and password (same as on brainbi.net) and get your bearer token in response.
      operationId: loginAndGetBearerToken
      parameters:
        - description: The same email you use for our platform.
          in: query
          name: email
          schema:
            example: "{{email}}"
            type: string
        - description: The password email you use for our platform.
          in: query
          name: password
          schema:
            example: "{{password}}"
            type: string
      responses:
        "200":
          description: ""
      summary: Login and get bearer token
  /api/logout:
    post:
      description: Once you are done, call this endpoint to lock your account!
      operationId: logout
      parameters:
        - description: The same email you use for our platform.
          in: query
          name: email
          schema:
            example: "{{email}}"
            type: string
      responses:
        "200":
          description: ""
      summary: Logout
  /api/orders:
    get:
      description: This resource lists all orders that are currently saved in your account.
      operationId: orders
      parameters:
        - in: query
          name: ""
          schema:
            example: ""
            type: string
      responses:
        "200":
          description: ""
      summary: Orders
      tags:
        - Orders
  /api/orders/1137:
    delete:
      description: Orders
      operationId: orders1
      parameters:
        - in: query
          name: ""
          schema:
            example: ""
            type: string
      requestBody:
        content:
          application/octet-stream: {}
      responses:
        "200":
          description: ""
      summary: Orders
      tags:
        - Orders
  /api/products:
    get:
      description: This resource lists all products that are currently saved in you account.
      operationId: products
      parameters:
        - in: query
          name: ""
          schema:
            example: ""
            type: string
      responses:
        "200":
          description: ""
      summary: Products
      tags:
        - Products
  /api/products/1137:
    delete:
      description: Products
      operationId: products1
      parameters:
        - in: query
          name: ""
          schema:
            example: ""
            type: string
      requestBody:
        content:
          application/octet-stream: {}
      responses:
        "200":
          description: ""
      summary: Products
      tags:
        - Products
  /api/rule:
    get:
      description: This resource lists all pricing rules that are currently saved in you account.
      operationId: rules
      parameters:
        - in: query
          name: ""
          schema:
            example: ""
            type: string
      responses:
        "200":
          description: ""
      summary: Rules
      tags:
        - Pricing Rules
  /api/rule/ruleData/1:
    get:
      description: This resource lists all data that wa saved for pricing rules.
      operationId: ruleData
      parameters:
        - in: query
          name: ""
          schema:
            example: ""
            type: string
      responses:
        "200":
          description: ""
      summary: Rule Data
      tags:
        - Pricing Rules
  /api/rule/ruleData/1/latest:
    get:
      description: This resource lists only the latest data point that wa saved for a pricing rule.
      operationId: ruleDataLatest
      parameters:
        - in: query
          name: ""
          schema:
            example: ""
            type: string
      responses:
        "200":
          description: ""
      summary: Rule Data Latest
      tags:
        - Pricing Rules
