swagger: "2.0"
basePath: /api
info:
  contact:
    x-twitter: amentumspace
  description: >
    Instantly access empirical models of atmospheric density and  composition that are recommended by the Committee on Space Research (COSPAR) for  satellite drag calculations. <br><br>

    <a href='https://ccmc.gsfc.nasa.gov/modelweb/atmos/nrlmsise00.html'>NRLMSISE-00</a> is recommended for composition calculations and was developed  by the US Naval Research Laboratory. <br><br>

    <a href='https://sol.spacenvironment.net/jb2008/'>JB2008</a> is a newer model and is
     recommended for density calculations at altitudes above 80 km. 
    It was developed by Space Environment Technologies and the US Air Force  Space Command. <br><br>

    We provide access to both models via an easy-to-use web API. <br><br>

    The API also automatically updates: <br>  - the indices needed by the JB2008 model to account for global density variations due to geomagnetic storms and EUV heating.  <br> - the Ap and F10.7 cm radio flux indices for the NRLMSISE00 model (unless provided by the user). <br><br>

    The API is rate limited to 10,000 calls per month for non commercial use.  Contact <a href="mailto:team@amentum.space">team@amentum.space</a> if you have  any questions or need to discuss commercial use and forecasting features. <br><br>

    Help us improve the quality of our web APIs by completing our 2 minute survey <a href="https://www.surveymonkey.com/r/CTDTRBN">here</a>.<br><br>

    Amentum Pty Ltd is not responsible nor liable for any loss or damage of any sort incurred as a result of using the API. <br><br>

    Copyright <a href='https://amentum.space'>Amentum Pty Ltd</a> 2020.
  title: >
    Atmosphere API - calculate composition and density of the atmosphere
  version: 1.0.0
  x-apisguru-categories:
    - location
  x-logo:
    url: https://twitter.com/amentumspace/profile_image?size=original
  x-origin:
    - format: swagger
      url: https://atmosphere.amentum.space/api/swagger.json
      version: "2.0"
  x-providerName: amentum.space
  x-serviceName: atmosphere
  x-preferred: false
consumes:
  - application/json
produces:
  - application/json
parameters:
  AP:
    description: >
      (Optional) The Ap-index provides a daily average level for geomagnetic activity F107, F107A, AP effects can be neglected below 80 km. If unspecified, the average of values in the 24 hours preceding the date-time  are automatically calculated from data provided by GFZ German Research Centre  for Geosciences.
    in: query
    name: ap
    required: false
    type: number
  Altitude:
    description: Altitude in (km)
    in: query
    name: altitude
    required: true
    type: number
  Day:
    description: Day in DD format
    in: query
    name: day
    required: true
    type: integer
  F107:
    description: >
      (Optional) Daily F10.7 cm radio flux for previous day (SFU). F107 and F107A values correspond to the 10.7 cm radio flux at the actual distance of Earth from Sun rather than radio flux at 1 AU. F107, F107A, AP effects can be neglected below 80 km. If unspecified, values provided by the US National Oceanic and  Atmospheric Administration are retrieved automatically.
    in: query
    name: f107
    required: false
    type: number
  F107A:
    description: >
      (Optional) 81 day average of F10.7 flux (SFU) centered on the specified day. F107 and F107A values correspond to the 10.7 cm radio flux at the actual distance of Earth from Sun rather than radio flux at 1 AU. F107, F107A, AP effects can be neglected below 80 km. If unspecified, values provided by the US National Oceanic and  Atmospheric Administration are retrieved automatically.
    in: query
    name: f107a
    required: false
    type: number
  GeodeticLatitude:
    description: GeodeticLatitude (deg) -90 to 90 deg
    in: query
    name: geodetic_latitude
    required: true
    type: number
  GeodeticLongitude:
    description: GeodeticLongitude (deg) 0 to 360 deg
    in: query
    name: geodetic_longitude
    required: true
    type: number
  Month:
    description: Month in MM format
    in: query
    name: month
    required: true
    type: integer
  UTC:
    description: Coordinated Universal Time (hrs)
    in: query
    name: utc
    required: true
    type: number
  Year:
    description: Year in YYYY format
    in: query
    name: year
    required: true
    type: integer
paths:
  /jb2008:
    get:
      description: >
        Computes<br><br>

        Exospheric temperature above the input position (K)<br><br>

        Temperature at the input position (K)<br><br>

        Total mass density at the input position (kg/m3)<br><br>

        Valid for altitudes in the interval [80, 40000] km
      operationId: app.api.endpoints.JB2008.sample_atmosphere
      parameters:
        - $ref: "#/parameters/Year"
        - $ref: "#/parameters/Month"
        - $ref: "#/parameters/Day"
        - $ref: "#/parameters/Altitude"
        - $ref: "#/parameters/GeodeticLatitude"
        - $ref: "#/parameters/GeodeticLongitude"
        - $ref: "#/parameters/UTC"
      responses:
        "200":
          description: Successful atmospheric density calculation
          schema:
            properties:
              at_alt_temp:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
              exospheric_temp:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
              total_mass_density:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
            type: object
      summary: Compute the JB2008 atmospheric density for given conditions
      tags:
        - Click to view documentation for API endpoints
  /nrlmsise00:
    get:
      description: >
        Computes <br>

        Number densities (/m3) of He, O, N2, O2, Ar, H, N. <br><br>

        Anomalous oxygen number density (/m3). <br><br>

        Exospheric temperature (K). <br><br>

        Temperature at altitude (K). <br><br>

        Total mass density (kg/m3). <br><br>

        Daily F10.7 cm radio flux (SFU) for previous day, obtained from the US National Oceanic and  Atmospheric Administration if not specified by the user. <br><br>

        81 day average of F10.7 flux (SFU) centered on the specified date, obtained from the US National Oceanic and  Atmospheric Administration if not specified by the user. <br><br>

        Average of ap values in the 24 hours preceding,  calculated from data provided by GFZ German Research Centre for Geosciences
         if not specified by the user. <br><br>



         
        Total mass density is the sum of the masses of the species in  equilibrium at the thermospheric temperature T(z) and the mass  density of the anomalous oxygen component. <br>

        Valid for altitudes in the interval [0, 1000] km.
      operationId: app.api.endpoints.NRLMSISE00.sample_atmosphere
      parameters:
        - $ref: "#/parameters/Year"
        - $ref: "#/parameters/Month"
        - $ref: "#/parameters/Day"
        - $ref: "#/parameters/Altitude"
        - $ref: "#/parameters/GeodeticLatitude"
        - $ref: "#/parameters/GeodeticLongitude"
        - $ref: "#/parameters/UTC"
        - $ref: "#/parameters/F107A"
        - $ref: "#/parameters/F107"
        - $ref: "#/parameters/AP"
      responses:
        "200":
          description: Successful atmospheric density calculation
          schema:
            properties:
              Ar_density:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
              H_density:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
              He_density:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
              N2_density:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
              N_density:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
              O2_density:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
              O_density:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
              anomalous_O_density:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
              ap:
                properties:
                  value:
                    type: number
                type: object
              at_alt_temp:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
              exospheric_temp:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
              f107:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
              f107a:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
              total_mass_density:
                properties:
                  units:
                    type: string
                  value:
                    type: number
                type: object
            type: object
      summary: Compute the NRLSMSIE-00 atmospheric composition and density for given conditions
      tags:
        - Click to view documentation for API endpoints
