openapi: 3.0.2
servers:
  - url: /.well-known/mercure
info:
  contact:
    email: dunglas+mercure@gmail.com
    name: Kévin Dunglas
    url: 'https://mercure.rocks'
  description: '[Mercure](https://mercure.rocks) is a protocol allowing to push data updates to web browsers and other HTTP clients in a convenient, fast, reliable and battery-efficient way.'
  license:
    name: GNU Affero General Public License v3.0 or later
    url: 'https://github.com/dunglas/mercure/blob/master/LICENSE'
    x-spdx: AGPL-3.0-or-later
  title: The Mercure protocol
  version: 0.3.2
  x-apisguru-categories:
    - messaging
  x-logo:
    backgroundColor: '#FFFFFF'
    url: 'https://raw.githubusercontent.com/dunglas/mercure/master/public/mercure.svg?sanitize=true'
  x-origin:
    - format: openapi
      url: 'https://raw.githubusercontent.com/dunglas/mercure/master/spec/openapi.yaml'
      version: '3.0'
  x-providerName: mercure.local
externalDocs:
  description: The Mercure protocol specification
  url: 'https://github.com/dunglas/mercure/blob/master/spec/mercure.md'
security:
  - Bearer: []
  - Cookie: []
paths:
  /:
    get:
      externalDocs:
        description: Sucbriptions specification
        url: 'https://github.com/dunglas/mercure/blob/master/spec/mercure.md#subscriptions'
      parameters:
        - description: 'The topic to get updates from, can be a URI template (RFC6570).'
          in: query
          name: topic
          required: true
          schema:
            items:
              type: string
            type: array
        - description: 'The last received event id, to retrieve missed events.'
          in: query
          name: Last-Event-ID
          schema:
            type: string
        - description: 'The last received event id, to retrieve missed events, takes precedence over the query parameter.'
          in: header
          name: Last-Event-ID
          schema:
            type: string
      responses:
        '200':
          content:
            text/event-stream: {}
          description: Event stream opened.
        '400':
          description: Missing topic parameter or invalid URI template.
        '401':
          description: Not authorized (missing or invalid JWT).
      summary: Subscribe to updates
    post:
      externalDocs:
        description: Publishing specification
        url: 'https://github.com/dunglas/mercure/blob/master/spec/mercure.md#publication'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                data:
                  description: The content of the new version of this topic.
                  type: string
                id:
                  description: 'The topic''s revision identifier: it will be used as the SSE''s `id` property.'
                  type: string
                retry:
                  description: The SSE's `retry` property (the reconnection time).
                  type: integer
                target:
                  description: 'Target audience of this update. If not provided, this update will be public.'
                  items:
                    type: string
                  type: array
                topic:
                  description: 'IRIs of the updated topic. If this key is present several times, the first occurrence is considered to be the canonical URL of the topic, and other ones are considered to be alternate URLs.'
                  items:
                    type: string
                  type: array
                type:
                  description: The SSE's `event` property (a specific event type).
                  type: string
              required:
                - topic
                - data
      responses:
        '200':
          content:
            text/plain: {}
          description: The id of this update
        '400':
          description: Invalid request
        '401':
          description: Not authorized (missing or invalid JWT)
      summary: Publish an update
components:
  securitySchemes:
    Bearer:
      bearerFormat: JWT
      description: Prefered for server to server
      scheme: bearer
      type: http
    Cookie:
      description: Prefered for web browsers
      in: cookie
      name: mercureAuthorization
      type: apiKey
