openapi: 3.0.0
servers:
  - url: http://libretranslate.local
info:
  title: LibreTranslate
  version: "1.0"
  x-apisguru-categories:
    - text
  x-origin:
    - format: swagger
      url: https://libretranslate.com/spec
      version: "2.0"
  x-providerName: libretranslate.local
paths:
  /frontend/settings:
    get:
      description: ""
      responses:
        "200":
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/frontend-settings"
          description: frontend settings
      summary: Retrieve frontend specific settings
      tags:
        - frontend
  /languages:
    get:
      description: ""
      responses:
        "200":
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/languages"
          description: List of languages
        "429":
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/error-slow-down"
          description: Slow down
      summary: Retrieve list of supported languages
      tags:
        - translate
  /translate:
    post:
      description: ""
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              example: es
              type: string
      responses:
        "200":
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/translate"
          description: Translated text
        "400":
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/error-response"
          description: Invalid request
        "429":
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/error-slow-down"
          description: Slow down
        "500":
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/error-response"
          description: Translation error
      summary: Translate text from a language to another
      tags:
        - translate
components:
  schemas:
    error-response:
      properties:
        error:
          description: Error message
          type: string
      type: object
    error-slow-down:
      properties:
        error:
          description: Reason for slow down
          type: string
      type: object
    frontend-settings:
      properties:
        charLimit:
          description: Character input limit for this language (-1 indicates no limit)
          type: integer
        language:
          properties:
            source:
              properties:
                code:
                  description: Language code
                  type: string
                name:
                  description: Human-readable language name (in English)
                  type: string
              type: object
            target:
              properties:
                code:
                  description: Language code
                  type: string
                name:
                  description: Human-readable language name (in English)
                  type: string
              type: object
          type: object
      type: object
    languages:
      items:
        properties:
          code:
            description: Language code
            type: string
          name:
            description: Human-readable language name (in English)
            type: string
        type: object
      type: array
    translate:
      properties:
        translatedText:
          description: Translated text(s)
          oneOf:
            - type: string
            - items: {}
              type: array
      type: object
